<%@ Page Title="About" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="Student_Management_System.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>About us</h2>
    <h3>&nbsp;</h3>
    <p><a href="https://localhost:44388/Default"> <img src ="https://static.goindigo.in/content/dam/indigov2/6e-website/aboutus/About-Us.jpg" alt ="Image-Not-Loaded" style="width: 1150px; height: 315px;" /></a></p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; margin-top: 14px; margin-bottom: 1rem; font-family: &quot;Open Sans&quot;, arial; font-size: 16px; line-height: 26px; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        IndiGo is India’s largest passenger airline with a market share of<b style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; font-weight: 700;">&nbsp;</b>53.9% as of December, 2020. We primarily operate in India’s domestic air travel market as a low-cost carrier with<span>&nbsp;</span><g class="gr_ gr_45 gr-alert gr_gramm gr_inline_cards gr_disable_anim_appear Grammar only-ins replaceWithoutSep" id="45" data-gr-id="45" style="box-sizing: border-box; -webkit-print-color-adjust: exact !important;">focus</g><span>&nbsp;</span>on our three pillars – offering low fares, being on-time and delivering a courteous and hassle-free experience. IndiGo has become synonymous with being on-time.</p>
    <p style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; margin-top: 14px; margin-bottom: 1rem; font-family: &quot;Open Sans&quot;, arial; font-size: 16px; line-height: 26px; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Since our inception in August 2006, we have grown from a carrier with one plane to a fleet of 285 aircraft today.&nbsp;A uniform fleet for each type of operation, high operational reliability and an award winning service make us one of the most reliable airlines in the world.</p>
    <p style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; margin-top: 14px; margin-bottom: 1rem; font-family: &quot;Open Sans&quot;, arial; font-size: 16px; line-height: 26px; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        IndiGo has a total destination count of 87 with 63 domestic destinations and 24 International. This includes one destination: Leh, which is&nbsp;now open&nbsp;for&nbsp;sale. &nbsp;Fourteen codeshare destinations beyond Istanbul on Turkish Airlines are also open for sale. They include, Athens (ATH), Budapest (BUD), Brussels (BRU), Tel Aviv (TLV) , Malta (MLA), Paris (CDG) , Dublin (DUB), Copenhagen (CPH) , Prague (PRG), Vienna (VIE), Zurich (ZRH), Amsterdam (AMS),London Gatwick (LGW) and London Heathrow (LHR) .</p>
    <h2 style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; margin-top: 40px; font-family: &quot;Open Sans&quot;, arial; margin-bottom: 12px; font-size: 26px; color: rgb(34, 34, 34); line-height: 21px; font-weight: 700; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="no-under-blue" style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; font-family: &quot;Open Sans&quot;, arial; font-size: 24px;">The Preferred Airline</span></h2>
    <p style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; margin-top: 14px; margin-bottom: 1rem; font-family: &quot;Open Sans&quot;, arial; font-size: 16px; line-height: 26px; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        IndiGo is not only the most efficient low fare operator domestically but is also comparable with global<span>&nbsp;</span><g class="gr_ gr_55 gr-alert gr_spell gr_inline_cards gr_disable_anim_appear ContextualSpelling multiReplace" id="55" data-gr-id="55" style="box-sizing: border-box; -webkit-print-color-adjust: exact !important;">low cost</g><span>&nbsp;</span>airlines. We are constantly enhancing our engagement with our passengers to augment their travel experience. From multichannel direct sales (including<span>&nbsp;</span><a adhocenable="false" href="https://www.goindigo.in/" style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; background: 0px 0px; outline: 0px; transition: color 200ms ease 0s; text-decoration: none; color: rgb(0, 122, 255);">online flight booking</a>, call<span>&nbsp;</span><g class="gr_ gr_54 gr-alert gr_spell gr_inline_cards gr_disable_anim_appear ContextualSpelling multiReplace" id="54" data-gr-id="54" style="box-sizing: border-box; -webkit-print-color-adjust: exact !important;">centers</g><span>&nbsp;</span>and 
        airport counters), to online flight status checking, an exclusive IndiGo app for Android, we have transformed air travel in India. Today, we are India’s most preferred airline. At IndiGo, low fares come with high quality.</p>
    <h2 style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; margin-top: 40px; font-family: &quot;Open Sans&quot;, arial; margin-bottom: 12px; font-size: 26px; color: rgb(34, 34, 34); line-height: 21px; font-weight: 700; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="no-under-blue" style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; font-family: &quot;Open Sans&quot;, arial; font-size: 24px;">Great Place to Work</span></h2>
    <p style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; margin-top: 14px; margin-bottom: 1rem; font-family: &quot;Open Sans&quot;, arial; font-size: 16px; line-height: 26px; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Being courteous and<span>&nbsp;</span><g class="gr_ gr_43 gr-alert gr_spell gr_inline_cards gr_disable_anim_appear ContextualSpelling ins-del multiReplace" id="43" data-gr-id="43" style="box-sizing: border-box; -webkit-print-color-adjust: exact !important;">hassle free</g><span>&nbsp;</span>starts with being a hassle-free place to work. A highly engaged and motivated workforce leads to higher levels of customer service. Our state-of-the-art ‘<g class="gr_ gr_44 gr-alert gr_spell gr_inline_cards gr_disable_anim_appear ContextualSpelling" id="44" data-gr-id="44" style="box-sizing: border-box; -webkit-print-color-adjust: exact !important;">ifly</g>’ facility is designed to deliver a real-time training experience to all our new recruits. This training facility is considered to be<span>&nbsp;</span><g class="gr_ gr_66 gr-alert gr_gramm gr_inline_cards gr_disable_anim_appear Grammar only-ins replaceWithoutSep" id="66" data-gr-id="66" style="box-sizing: border-box; -webkit-print-color-adjust: exact !important;">one</g><span>&nbsp;</span>the 
        best aviation training facilities in India. With our people-friendly culture at the heart of all we do, we continuously help the company staff find work-life balance.&nbsp;Ten years in a row, IndiGo continues to be amongst the best organizations to work for in India and has been named Aon’s Best Employer, 2017</p>
    <h2 style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; margin-top: 40px; font-family: &quot;Open Sans&quot;, arial; margin-bottom: 12px; font-size: 26px; color: rgb(34, 34, 34); line-height: 21px; font-weight: 700; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="no-under-blue" style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; font-family: &quot;Open Sans&quot;, arial; font-size: 24px;">IndiGoReach</span></h2>
    <p style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; margin-top: 14px; margin-bottom: 1rem; font-family: &quot;Open Sans&quot;, arial; font-size: 16px; line-height: 26px; color: rgb(34, 34, 34); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Our Corporate Social Responsibility (CSR) initiative IndiGoReach focuses on three broad themes: Children and Education, Women Empowerment and Environment.&nbsp;We work towards upliftment of communities not just around us but also far-flung areas in the country. After all, India’s holistic progress is rooted in the collective aspirations of its people.</p>
    <h2 style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; margin-top: 40px; font-family: &quot;Open Sans&quot;, arial; margin-bottom: 12px; font-size: 26px; color: rgb(34, 34, 34); line-height: 21px; font-weight: 700; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="no-under-blue" style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; font-family: &quot;Open Sans&quot;, arial; font-size: 24px;">Facts and Figures</span></h2>
    <ul style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; margin-top: 20px; margin-bottom: 1rem; padding-left: 20px; color: rgb(34, 34, 34); font-family: &quot;Open Sans&quot;, arial; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <li style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; font-size: 16px !important; margin-bottom: 11px !important; line-height: 1.86; color: rgb(85, 85, 85);">10 consecutive years of Profitable operations</li>
        <li style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; font-size: 16px !important; margin-bottom: 11px !important; line-height: 1.86; color: rgb(85, 85, 85);">Market share of&nbsp;53.9% as of December, 2020.</li>
        <li style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; font-size: 16px !important; margin-bottom: 11px !important; line-height: 1.86; color: rgb(85, 85, 85);">Fleet&nbsp;of 285 aircraft including 120 new&nbsp;generation&nbsp;A320 NEOs, 111 A320 CEOs, 25 ATRs and 29 A321 NEO.</li>
        <li style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; font-size: 16px !important; margin-bottom: 11px !important; line-height: 1.86; color: rgb(85, 85, 85);">Recognized as ‘Great Place to Work for in India’ for 8 years in a row (2008- 2015)</li>
        <li style="box-sizing: border-box; -webkit-print-color-adjust: exact !important; font-size: 16px !important; margin-bottom: 11px !important; line-height: 1.86; color: rgb(85, 85, 85);">Named as Aon’s Best Employer for the year 2016 and 2017</li>
    </ul>
    <a href="https://localhost:44388/Default">&nbsp;</a>
</asp:Content>
